version: '3.8'

services:
  reverse-proxy:
    image: nginx:stable-alpine
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      web-services:
        aliases:
          - backend.${BACKEND_DOMAIN:-127-0-0-1.sslip.io}

  db:
    image: postgres:latest
    container_name: postgres_server
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - web-services

  backend:
    build: backend
    restart: always
    environment:
      DB_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - web-services
 

networks:
  web-services:
    driver: bridge

volumes:
  postgres-data: